In [2]:
import numpy as np

In [20]:
M1 = np.array([[1,2,3,4],
               [1,2,3,4],
               [1,2,3,4]])
M2 = np.array([4,5,6])
print(np.sum(M1, axis=1))
print(M1 *M1)
print(M1.shape[1])

[10 10 10]
[[ 1  4  9 16]
 [ 1  4  9 16]
 [ 1  4  9 16]]
4


In [16]:
def CosineProximity_p(y, t):
    '''
        dCdy = CosineProximity_p(y, t)
        
        Computes the gradient of the cosine proximity cost function.
        
        Inputs:
          y is a batch of samples, with samples stored in rows
          t is a batch of targets
          
        Output:
          dCdy is an array the same size as y, holding the derivative
               of the cost with respect to each element in y
    '''
    
    # ***** YOUR CODE HERE *****
    
    dCdy = (CosineProximity(y, t)*(y/np.power(np.linalg.norm(y), 2))-
            t/(np.linalg.norm(y, axis=1)* np.linalg.norm(t, axis=1)))/ Network.NSamples(y)
    
    return dCdy
def CosineProximity(y, t):
    '''
        C = CosineProximity(y, t)
        
        Evaluates the average cosine proximity for the batch.
        
        Inputs:
          y is a batch of samples, with samples stored in rows
          t is a batch of targets
          
        Output:
          C is the average cosine proximity (cost)
    '''
    C = -np.sum(y*t, axis=1)
    C /= np.linalg.norm(y, axis=1)
    C /= np.linalg.norm(t, axis=1)
    return np.sum(C) / Network.NSamples(y)


In [18]:
y = np.array([[1,2,3,4],
    [2,3,4,5],
    [5,6,7,8]])
t = np.array([[2,3,4,5],
    [5,6,7,8],
    [6,7,8,9]])

print(CosineProximity_p(y, t))

TypeError: ufunc 'true_divide' output (typecode 'd') could not be coerced to provided output parameter (typecode 'l') according to the casting rule ''same_kind''

In [11]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([1,1,1])
print(np.dot(b,a))

ValueError: shapes (3,) and (2,3) not aligned: 3 (dim 0) != 2 (dim 0)